# Generated by Django 4.2.11 on 2024-03-15 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(editable=False, max_length=21, unique=True, verbose_name='Reference')),
                ('driverId', models.IntegerField(verbose_name='Driver ID')),
                ('constructorId', models.IntegerField(verbose_name='Constructor ID')),
                ('circuitId', models.IntegerField(verbose_name='Circuit Id')),
                ('raceRound', models.IntegerField(verbose_name='Race round')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('createdDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updateDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('isArchived', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
