# Generated by Django 4.2.11 on 2024-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictorrequest',
            name='predicted_rank',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Prediction'),
        ),
        migrations.AddField(
            model_name='predictorrequest',
            name='status',
            field=models.CharField(default='New', max_length=20, verbose_name='Status'),
        ),
    ]
