# Generated by Django 4.2.11 on 2024-03-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_predictorrequest_predicted_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictorrequest',
            name='errorMessage',
            field=models.TextField(blank=True, null=True, verbose_name='Error Message'),
        ),
    ]
