# Generated by Django 4.2.11 on 2024-03-15 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructorId', models.IntegerField(verbose_name='Constructor ID')),
                ('constructor_name', models.CharField(max_length=80, verbose_name='Name')),
                ('constructor_country', models.CharField(max_length=120, verbose_name='Country')),
                ('constructor_is_active', models.IntegerField(verbose_name='Is active')),
                ('constructor_races_won', models.IntegerField(verbose_name='Number of races won')),
                ('constructor_avg_point', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Constructor AVG points')),
                ('constructor_times_in_top_10', models.IntegerField(verbose_name='Number the time in the top 10')),
                ('createdDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updateDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('isArchived', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
