# Generated by Django 4.2.11 on 2024-03-16 00:15

import constructors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='logo',
            field=models.FileField(null=True, upload_to=constructors.models.logo_path),
        ),
    ]
