# Generated by Django 4.2.11 on 2024-03-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0002_constructor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='constructor_avg_point',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Constructor AVG points'),
        ),
    ]
