# Generated by Django 4.2.11 on 2024-03-15 22:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverId', models.IntegerField(null=True, verbose_name='Driver ID')),
                ('number', models.CharField(max_length=5, null=True, verbose_name='Driver number')),
                ('nationality', models.CharField(max_length=80, null=True, verbose_name='Nationality')),
                ('driver_is_active', models.IntegerField(verbose_name='Is active')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('full_name', models.CharField(max_length=250, null=True, verbose_name='Driver Name')),
                ('driver_avg_point', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Points AVG')),
                ('driver_avg_speed', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Speed AVG')),
                ('race_end_bf_2015', models.IntegerField(null=True, verbose_name='Race ends before 2015')),
                ('race_end_in_2015', models.IntegerField(null=True, verbose_name='Race ends in 2015')),
                ('race_end_in_2016', models.IntegerField(null=True, verbose_name='Race ends in 2016')),
                ('race_end_in_2017', models.IntegerField(null=True, verbose_name='Race ends in 2017')),
                ('race_end_in_2018', models.IntegerField(null=True, verbose_name='Race ends in 2018')),
                ('race_end_in_2019', models.IntegerField(null=True, verbose_name='Race ends in 2019')),
                ('race_end_in_2020', models.IntegerField(null=True, verbose_name='Race ends in 2020')),
                ('race_end_in_2021', models.IntegerField(null=True, verbose_name='Race ends in 2021')),
                ('race_end_in_2022', models.IntegerField(null=True, verbose_name='Race ends in 2022')),
                ('race_end_in_2023', models.IntegerField(null=True, verbose_name='Race ends in 2023')),
                ('driver_most_won_circuit_id', models.IntegerField(null=True, verbose_name='Most won circuit ID')),
                ('driver_nber_of_races_won', models.IntegerField(null=True, verbose_name='Number of races won')),
                ('driver_nber_of_times_in_top_10', models.IntegerField(null=True, verbose_name='Number of time in the top 10')),
                ('createdDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updateDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('isArchived', models.BooleanField(blank=True, default=False)),
                ('constructorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructors.constructor')),
            ],
        ),
    ]
