# Generated by Django 4.2.11 on 2024-03-16 00:15

from django.db import migrations, models
import drivers.models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='picture',
            field=models.FileField(null=True, upload_to=drivers.models.picture_path),
        ),
    ]
