# Generated by Django 4.2.11 on 2024-03-16 12:11

from django.db import migrations, models
import drivers.models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_constructorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=drivers.models.picture_path),
        ),
    ]
