# Generated by Django 4.2.11 on 2024-03-16 16:22

import circuits.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuitId', models.IntegerField(unique=True, verbose_name='Circuit ID')),
                ('name', models.CharField(max_length=100, verbose_name='Circuit Name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Longitude')),
                ('circuits_is_active', models.IntegerField(verbose_name='Is active')),
                ('createdDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updateDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('isArchived', models.BooleanField(blank=True, default=False)),
                ('picture', models.FileField(blank=True, null=True, upload_to=circuits.models.circuit_path)),
            ],
        ),
    ]
