# Generated by Django 4.2.11 on 2024-03-17 18:27

import circuits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='card_img',
            field=models.FileField(blank=True, null=True, upload_to=circuits.models.circuit_card_path),
        ),
        migrations.AddField(
            model_name='circuit',
            name='country_img',
            field=models.FileField(blank=True, null=True, upload_to=circuits.models.circuit_country_path),
        ),
    ]
