# Generated by Django 4.2.11 on 2024-05-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0002_circuit_card_img_circuit_country_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='raceRound',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Round'),
        ),
    ]
